CREATE DATABASE Cricket_info;
USE Cricket_info;
CREATE TABLE Sports_info(id int,sport_type varchar(10),Player_name varchar(20),DOB DATE,Age int,Gender Char(10),Birth_place varchar(20),Country Varchar(20),Nickname varchar(20),Roles varchar(15));
SELECT * FROM Sports_info;
ALTER TABLE Sports_info ADD COLUMN(International_runs int);
DESC Sports_info;
ALTER TABLE Sports_info RENAME COLUMN id to sports_id;
ALTER TABLE Sports_info RENAME COLUMN DOB to Date_of_Birth;
INSERT INTO Sports_info VALUES(101,'Cricket','Sachin Tendulkar', '1973-04-24', 48, 'Male', 'Mumbai', 'India', 'Little Master', 'Test', 15921);
INSERT INTO Sports_info VALUES(102,'Cricket','Virat Kohli', '1988-11-05', 34, 'Male', 'Delhi', 'India', 'King Kohli', 'Batsman', 12169);
INSERT INTO Sports_info VALUES(103,'Cricket','Ricky Ponting', '1974-12-19', 48, 'Male', 'Launceston', 'Australia', 'Punter', 'Batsman', 13378);
INSERT INTO Sports_info VALUES(104,'Cricket','Kane Williamson', '1990-08-08', 33, 'Male', 'Tauranga', 'New Zealand', 'Kane-o', 'Batsman',  7337);
INSERT INTO Sports_info VALUES(105,'Cricket','AB de Villiers', '1984-02-17', 39, 'Male', 'Pretoria', 'South Africa', 'Mr. 360', 'Batsman',  9577);
INSERT INTO Sports_info VALUES(106,'Cricket','Jacques Kallis', '1975-10-16', 47, 'Male', 'Pinelands', 'South Africa', 'King Kallis', 'All-Rounder', 13289);
INSERT INTO Sports_info VALUES(107,'Cricket','Wasim Akram', '1966-06-03', 57, 'Male', 'Lahore', 'Pakistan', 'Sultan of Swing', 'Bowler',  414);
INSERT INTO Sports_info VALUES(108,'Cricket','Muttiah Muralitharan', '1972-04-17', 51, 'Male', 'Kandy', 'Sri Lanka', 'Murali', 'Bowler', 1267);
INSERT INTO Sports_info VALUES(109,'Cricket','Shane Warne', '1969-09-13', 53, 'Male', 'Melbourne', 'Australia', 'Warnie', 'Bowler', 1001);
INSERT INTO Sports_info VALUES(110,'Cricket','Imran Khan', '1952-10-05', 70, 'Male', 'Lahore', 'Pakistan', 'Kaptaan', 'All-Rounder',  3807);
DELETE FROM Sports_info WHERE sports_id=110;
DELETE FROM Sports_info WHERE Player_name='Wasim Akram';
SELECT *FROM Sports_info WHERE Roles='Batsman' AND Country='India' AND sports_id='102'; 
SELECT *FROM Sports_info WHERE Roles='Batsman' OR Country='India' OR sports_id='102';
SELECT *FROM Sports_info WHERE AGE IN(48,34);
SELECT *FROM Sports_info WHERE sports_id IN (101,102,103);
SELECT *FROM Sports_info WHERE Player_name IN('Virat Kohli' ,'Ricky Ponting');
SELECT *FROM Sports_info WHERE Roles NOT IN('Batsman','Test');
SELECT *FROM Sports_info WHERE AGE NOT IN (47,51,53);
SELECT *FROM Sports_info WHERE AGE NOT IN (47,51,53);
UPDATE Sports_info SET Roles='Test' WHERE Roles='Batsman';
UPDATE Sports_info SET Roles='Batsman' WHERE Roles='Test';
UPDATE Sports_info SET Nickname='Punter' WHERE Nickname='Player';
UPDATE Sports_info SET Nickname='Little Master' WHERE Roles='Master';
UPDATE Sports_info SET sports_id=101 WHERE sports_id=100;
UPDATE Sports_info SET sports_id=107 WHERE sports_id=108;
UPDATE Sports_info SET  International_runs=15921 WHERE International_runs=16000 ;
UPDATE Sports_info SET  International_runs=12169 WHERE International_runs=16001 ;
UPDATE Sports_info SET  Birth_place='Mumbai' WHERE Birth_place='Delhi' ;
UPDATE Sports_info SET  Birth_place='Kandy' WHERE Birth_place='Delhi' ;
UPDATE Sports_info SET  sport_type='Football',Player_name='ronaldo',Roles='Striker' WHERE sports_id=105 ;
UPDATE Sports_info SET  sport_type='Basketball',Player_name='jordon',Roles='Forward' WHERE sports_id=106 ;
UPDATE Sports_info SET  sport_type='Baseball',Player_name='james',Roles='Setup' WHERE sports_id=107 ;
UPDATE Sports_info SET  sport_type='Basketball' WHERE sports_id=106 ;
UPDATE Sports_info SET  sport_type='Baseball' WHERE sports_id=107 ;

SELECT *FROM Sports_info;